apiVersion: v1
kind: Secret
metadata:
  name: users-service-secrets
  namespace: production
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=tech-challenge-users.cauxpuca0lvv.us-east-1.rds.amazonaws.com,1433;Database=tech-challenge-users;User Id=admin;Password=FCG_Password;TrustServerCertificate=True;"
  
  JwtSettings__Secret: "BPDMN0XwJiOS9JT8ssimWLYLT4LurB9GvdImjAoYfWs="
  
  AWS_ACCESS_KEY_ID: "ASIAWHV7Z2B7FFYR74UU"
  AWS_SECRET_ACCESS_KEY: "MJMnTG3yRYutbmevdJa9NNeTfi60AU4UtxWjHOtj"