apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: production
  labels:
    app: payments-service
spec:
  type: NodePort
  selector:
    app: payments-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 30081
  sessionAffinity: None
---
# Service interno
apiVersion: v1
kind: Service
metadata:
  name: payments-service-internal
  namespace: production
  labels:
    app: payments-service
spec:
  type: ClusterIP
  selector:
    app: payments-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP